<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headLink()->appendStylesheet($this->assetUrl('css/lightslider.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/lightgallery.min.css'));
$this->headScript()->appendFile($this->assetUrl('js/lightslider.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lightgallery.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-video.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-zoom.js'));

$lightMedia = [];
$otherMedia = [];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if ((strpos($mediaType, 'image/') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $lightMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
?>

<div class="item-container">
    <div id="left">
    <?php if (count($lightMedia) > 0): ?>
        <ul id="itemfiles" class="media-list">
    <?php foreach ($lightMedia as $media): ?>
        <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
            <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('medium')); ?>" class="media resource">
        <?php echo $media->render(); ?>
            </li>
    <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    </div>

    <div id="right">
        <?php
        $collection=[];
        $series=[];
        foreach ($item->itemSets() as $itemSet){
            $resource_class = $itemSet->displayResourceClassLabel();

            switch ($resource_class) {
                case 'Series':
                    array_push($series, $itemSet);
                    break;

                case 'Collection':
                    array_push($collection, $itemSet);
                    break;
            }
        }?>

        <div class="property">
            <h4>컬렉션</h4>
            <div class="values">
            <?php foreach ($collection as $itemSet): ?>
                <div class="value">
                <?php echo sprintf('%s&nbsp;<a href="%s">▶</a>', $itemSet->value('dcterms:title'), $itemSet->url()); ?>
                </div>
            <?php endforeach ?>
            </div>
        </div>
        
        <div class="property">
            <h4>시리즈</h4>
            <div class="values">
            <?php foreach ($series as $itemSet): ?>
                <div class="value">
                <?php echo sprintf('%s&nbsp;<a href="%s">▶</a>', $itemSet->value('dcterms:title'), $itemSet->url()); ?>
                </div>
            <?php endforeach ?>
            </div>
        </div>

        <?php echo $item->displayValues(); ?>

        <?php if (count($otherMedia) > 0): ?>
        <div id="other-media" class="property">
            <h4><?php echo $this->translate('Other Media'); ?></h4>
            <?php foreach($otherMedia as $media): ?>
            <div class="value">
                <a href="<?php echo $media->siteUrl(); ?>"><?php echo $media->displayTitle(); ?></a>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>

        <?php $xml = sprintf('/omeka/unapi?id=%s&format=rdf_dc', $item->id()); ?>
        <div class="property">
            <h4>내려받기</h4>
            <div class="values">
                <div class="value"><a href="<?php echo $xml ?>">Dublin Core 1.1 XML</a></div>
            </div>
        </div>
        <?php $this->trigger('view.show.after'); ?>
    </div>
</div>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>

<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>


