<div class="item-showcase">
<?php foreach ($attachments as $attachment): ?>
    <div class="item resource">
    <?php
    $item = $attachment->item();
    if ($item):
    ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media):
            // echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
            echo $this->thumbnail($media, $this->thumbnailType);
        endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <?php echo $item->linkRaw('<div class="cover"><p>'.$item->displayTitle().'</p></div>'); ?>
        <?php elseif ($showTitleOption == 'file_name'): ?>
		<?php echo $item->linkRaw('<div class="cover"><p>'.$media->displayTitle().'</p></div>'); ?>
        <?php endif; ?>
    <?php endif; ?>

    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
